name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: DockerHub Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/order_manager:latest

      - name: SSH key setup
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}

      - name: Deploy to server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} << 'EOF'
            # Navigate to the correct application directory
            cd ${{ secrets.EC2_APP_DIR }}
          
            echo "Waiting 20 seconds for the Docker image to replicate..."
            sleep 20
          
            echo "Downloading the new image from Docker Hub..."
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/order-manager:latest
          
            # Load variables from the .env file into the shell environment
            echo "Loading production environment variables..."
            export $(grep -v '^#' .env | xargs)

            # Build the database URL in a separate variable for robustness
            echo "Building the database URL for migration..."
            DATABASE_URL="postgres://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}?sslmode=disable"
          
            # Run the migration using the variable, properly quoted
            echo "Running database migrations..."
            docker run --rm --network host -v $(pwd)/infrastructure/db/migrations:/migrations \
            migrate/migrate -path /migrations -database "${DATABASE_URL}" up
          
            echo "Starting the application with Docker Compose..."
            docker compose -f docker-compose.prod.yml up -d --remove-orphans
          
            echo "Cleaning up old images..."
            docker image prune -af
          EOF