name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build and Deploy on EC2
    runs-on: ubuntu-latest

    steps:
      - name: go config
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Checkout code
        uses: actions/checkout@v4

      - name: building
        run: go build -v -o order_manager ./cmd/order_manager

      - name: config ssh key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}

      - name: Deploy to EC2
        run: |
          scp -o StrictHostKeyChecking=no ./order_manger ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }}:${{ secrets.EC2_APP_DIR }}/order_manager
          

      - name: Reiniciar a aplicação na EC2
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} 'sudo systemctl restart order_manager'
